version: '3'
services:
  php:
    image: php__image
    container_name: php-tw-bbs
    build:
      context: .
      dockerfile: ./docker/Dockerfile_php

    ports:
      - 80:9000

    volumes:
      - ./app:/var/www/html

    env_file:
      - .env

    tty: true
    depends_on:
      - db

  db:
    image: mysql:8.0.12
    container_name: mysql-tw-bbs
    ports:
      - '3306:3306'
    volumes:
      - data-volume:/var/lib/mysql
      - ./docker/stat/my.cnf:/etc/mysql/conf.d/my.cnf

    environment:
      MYSQL_DATABASE: bbs_tw
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'

    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin  
    container_name: phpmyadmin-tw-bbs
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "1000:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
volumes:
 data-volume:
